import type { LetterUnit } from "./types";

// Contenido extraído fielmente de reference/Argentina-Cuadernillo-1 (1).pdf, páginas 3-21.
// Cada unidad = 1 letra nueva; los ejercicios de lectura solo usan letras ya vistas,
// igual que en el cuadernillo original.
export const letterUnits: LetterUnit[] = [
  {
    id: "a",
    order: 1,
    grafemas: ["A", "a", "Á", "á"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "a",
    lectura: {
      grid: [
        ["á", "á", "a", "a", "a", "á"],
        ["a", "á", "á", "a", "á", "a"],
        ["á", "á", "á", "a", "á", "á"],
        ["a", "a", "a", "á", "a", "a"],
      ],
      palabras: [],
      oraciones: [],
    },
    escritura: {
      trazos: ["A", "Á", "a", "á"],
      palabraFinal: [],
    },
  },
  {
    id: "m",
    order: 2,
    grafemas: ["M", "m"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "mmm",
    lectura: {
      grid: [
        ["ma", "má", "am", "am", "ám", "ám"],
        ["ám", "ma", "má", "má", "am", "ma"],
        ["ám", "ma", "má", "am", "am", "má"],
        ["má", "am", "ma", "ám", "ám", "ma"],
      ],
      palabras: ["ma", "ama", "mamá"],
      oraciones: ["Mamá ama.", "Ama a mamá."],
    },
    escritura: {
      trazos: ["M", "m"],
      palabraFinal: ["mamá"],
    },
  },
  {
    id: "e",
    order: 3,
    grafemas: ["E", "e", "É", "é"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "e",
    lectura: {
      grid: [
        ["em", "e", "é", "me", "me", "me"],
        ["e", "e", "me", "em", "em", "é"],
        ["em", "é", "em", "me", "e", "é"],
        ["e", "em", "é", "é", "e", "me"],
      ],
      palabras: ["me", "eme"],
      oraciones: ["Mamá me ama.", "Me ama mamá."],
    },
    escritura: {
      trazos: ["E", "É", "e", "é"],
      palabraFinal: ["eme"],
    },
  },
  {
    id: "o",
    order: 4,
    grafemas: ["O", "o", "Ó", "ó"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "o",
    lectura: {
      grid: [
        ["ó", "mó", "om", "mó", "om", "mó"],
        ["mo", "ó", "o", "mo", "ó", "o"],
        ["ó", "o", "mó", "o", "mo", "om"],
        ["om", "mo", "o", "mó", "om", "ó"],
      ],
      palabras: ["amo"],
      oraciones: ["Amo a mamá."],
    },
    escritura: {
      trazos: ["O", "Ó", "o", "ó"],
      palabraFinal: [],
    },
  },
  {
    id: "s",
    order: 5,
    grafemas: ["S", "s"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "sa",
    lectura: {
      grid: [
        ["es", "os", "sa", "sa", "as", "so"],
        ["as", "as", "se", "so", "sé", "es"],
        ["sa", "es", "sé", "so", "se", "os"],
      ],
      palabras: [
        "se", "es", "sé", "ese",
        "oso", "eso", "esa", "asa",
        "sea", "mes", "más", "ase",
        "mesa", "osos", "esos", "masa",
        "esas", "seas", "aseo", "somos",
        "asoma", "meses", "amasa", "mesas",
      ],
      oraciones: ["Mamá amasa.", "¡Ese oso amasa!"],
    },
    escritura: {
      trazos: ["S", "s"],
      palabraFinal: ["mesa", "osos"],
    },
  },
  {
    id: "n",
    order: 6,
    grafemas: ["N", "n"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "na",
    lectura: {
      grid: [
        ["né", "on", "no", "ná", "on", "ón"],
        ["ón", "an", "no", "an", "nó", "nó"],
        ["en", "en", "na", "ne", "na", "né"],
      ],
      palabras: [
        "en", "no", "son", "nos",
        "nena", "mano", "mono", "mona",
        "aman", "sean", "sano", "sana",
        "sonó", "enano", "manos", "menos",
        "monos", "nenas", "manso", "monas",
        "semana", "asoman", "mansos", "semanas",
      ],
      oraciones: ["Somos monos mansos.", "Mamá ama a Ana. Ana ama a mamá."],
    },
    escritura: {
      trazos: ["N", "n"],
      palabraFinal: ["nena", "mano"],
    },
  },
  {
    id: "p",
    order: 7,
    grafemas: ["P", "p"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "pa",
    lectura: {
      grid: [
        ["pó", "pa", "ep", "ep", "ap", "pé"],
        ["po", "op", "pé", "pá", "pa", "pó"],
        ["ap", "pe", "pe", "op", "po", "pá"],
      ],
      palabras: [
        "pan", "papa", "pone", "mapa",
        "pena", "sopa", "pesa", "peso",
        "paso", "pasa", "sapo", "papá",
        "ponen", "paseo", "pasos", "ponés",
        "pasan", "sapos", "mapas", "papas",
        "pesos", "pensó", "espesa", "ponemos",
      ],
      oraciones: ["Ana pensó en papá.", "Papá ama a mamá.", "Papá pasea a Pepe."],
    },
    escritura: {
      trazos: ["P", "p"],
      palabraFinal: ["pan", "mapa"],
    },
  },
  {
    id: "i",
    order: 8,
    grafemas: ["I", "i", "Í", "í"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "i",
    lectura: {
      grid: [
        ["í", "mí", "mi", "sí", "mí", "i"],
        ["si", "sí", "im", "ni", "pí", "í"],
        ["pi", "ip", "ni", "is", "ip", "in"],
      ],
      palabras: [
        "ni", "mi", "si", "mí",
        "sí", "así", "pie", "sin",
        "mis", "mía", "mías", "mío",
        "míos", "papi", "mimo", "mami",
        "pies", "seis", "piso", "piano",
        "peina", "mismo", "misma", "pepino",
        "anima", "pienso", "mismos", "Nina",
      ],
      oraciones: ["Mi papá es Pepe.", "Nina pisó mi pie.", "Mamá me peina.", "Mi papá me anima."],
    },
    escritura: {
      trazos: ["I", "Í", "i", "í"],
      palabraFinal: ["pies"],
    },
  },
  {
    id: "y",
    order: 9,
    grafemas: ["Y", "y"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "ya",
    fonemaRecordingKey: "y-i",
    lectura: {
      grid: [
        ["ey", "ey", "ey", "oy", "oy", "ey"],
        ["ey", "oy", "oy", "oy", "oy", "oy"],
        ["ey", "oy", "ey", "ey", "oy", "ey"],
      ],
      palabras: ["y", "soy"],
      oraciones: [
        "Soy mamá.",
        "Soy una nena.",
        "Mis papás me aman.",
        "Son nenas y nenes.",
        "Mis papás amasan pan y pisan papas.",
        "Mis manos y mis pies.",
      ],
    },
    escritura: {
      trazos: ["Y", "y"],
      palabraFinal: ["soy"],
    },
  },
  {
    id: "l",
    order: 10,
    grafemas: ["L", "l"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "la",
    lectura: {
      grid: [
        ["el", "le", "lí", "ol", "lá", "li"],
        ["la", "lé", "ló", "lá", "la", "il"],
        ["ol", "al", "lo", "lé", "él", "lí"],
      ],
      palabras: [
        "la", "el", "al", "le",
        "él", "ola", "ala", "mil",
        "los", "las", "sol", "les",
        "sal", "lee", "pala", "miel",
        "solo", "papel", "salsa", "paloma",
        "molino", "lo", "ley", "leo",
        "salió", "sopla", "limpia", "leona",
      ],
      oraciones: ["El oso lame la miel.", "Papá lee el papel.", "Paloma limpia la mesa."],
    },
    escritura: {
      trazos: ["L", "l"],
      palabraFinal: ["miel", "pelo"],
    },
  },
  {
    id: "u",
    order: 11,
    grafemas: ["U", "u", "Ú", "ú"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "u",
    lectura: {
      grid: [
        ["ú", "lu", "lu", "ul", "um", "nú"],
        ["up", "us", "u", "pu", "un", "up"],
        ["nu", "ul", "mu", "su", "un", "mu"],
      ],
      palabras: [
        "un", "su", "una", "sus",
        "uno", "usa", "une", "uso",
        "aún", "muy", "unos", "unas",
        "puso", "suma", "lupa", "puma",
        "unen", "usan", "menú", "lunes",
        "pulpo", "museo", "espuma", "luminosa",
        "suelo", "luna", "sumas", "suena",
      ],
      oraciones: [
        "Nina lee el menú.",
        "Esta no es su mesa.",
        "Paloma suma uno más uno.",
        "Pepe pasea en un museo.",
        "La nena pisó el suelo limpio.",
        "La luna es luminosa.",
        "Ana usó una lupa.",
      ],
    },
    escritura: {
      trazos: ["U", "Ú", "u", "ú"],
      palabraFinal: ["suma"],
    },
  },
  {
    id: "c",
    order: 12,
    grafemas: ["C", "c"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "ca",
    fonemaRecordingKey: "c-k",
    lectura: {
      grid: [
        ["có", "ac", "cú", "ca", "cu", "uc"],
        ["ec", "ic", "oc", "co", "cá", "ic"],
      ],
      palabras: [
        "con", "poco", "casa", "como",
        "casi", "cama", "pico", "cosa",
        "cómo", "coco", "capa", "cuna",
        "escuela", "película", "calma", "música",
        "pocas", "espinacas", "campeón", "camina",
        "camión", "campana", "seco", "comes",
      ],
      oraciones: ["La escuela me calma.", "Como espinacas con mi papá.", "Camilo camina en la colina."],
    },
    escritura: {
      trazos: ["C", "c"],
      palabraFinal: ["casa", "cama"],
    },
  },
  {
    id: "d",
    order: 13,
    grafemas: ["D", "d"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "da",
    lectura: {
      grid: [
        ["od", "da", "de", "di", "de", "ed"],
        ["ud", "ad", "id", "ud", "do", "du"],
      ],
      palabras: [
        "de", "da", "di", "del",
        "dos", "dan", "día", "cada",
        "nada", "desde", "nido", "lado",
        "pide", "idea", "nudo", "dedo",
        "nadie", "media", "cuando", "saludo",
        "moneda", "donde", "mundo", "saluda",
        "anda", "duende", "dio", "pescado",
      ],
      oraciones: [
        "Paloma saludó a Lucas.",
        "Mamá nos dio limonada.",
        "Este lunes es un día de descanso.",
        "Esa media es de mamá.",
      ],
    },
    escritura: {
      trazos: ["D", "d"],
      palabraFinal: ["idea", "dedo"],
    },
  },
  {
    id: "t",
    order: 14,
    grafemas: ["T", "t"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "ta",
    lectura: {
      grid: [
        ["tó", "at", "tá", "tú", "ot", "et"],
        ["té", "tí", "ut", "te", "ta", "tu"],
      ],
      palabras: [
        "tu", "tú", "té", "ten",
        "tus", "nota", "alto", "moto",
        "esta", "este", "esto", "todo",
        "está", "tiene", "tanto", "antes",
        "siete", "punto", "tiempo", "cuento",
        "momento", "cuántos", "adelante", "distinto",
        "mete", "alimentó", "tía", "título",
      ],
      oraciones: [
        "Me senté a la mesa.",
        "Papá nos lee un cuento.",
        "Esta música es linda.",
        "Lucas está en la escuela.",
      ],
    },
    escritura: {
      trazos: ["T", "t"],
      palabraFinal: ["alto", "auto"],
    },
  },
  {
    id: "b",
    order: 15,
    grafemas: ["B", "b"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "ba",
    lectura: {
      grid: [
        ["ub", "ib", "bi", "ba", "bo", "eb"],
        ["ob", "bu", "ab", "be", "bó", "bé"],
      ],
      palabras: [
        "cubo", "sabe", "sube", "lobo",
        "nube", "bebé", "bien", "saben",
        "subió", "cambia", "estaba", "escoba",
        "cambio", "subido", "debo", "busca",
        "pasaba", "sabemos", "buenas", "abuela",
        "bonito", "subimos", "tocaba", "cambian",
        "acabó", "loba", "abuelo", "bonita",
      ],
      oraciones: [
        "La loba saluda a la Luna.",
        "Sebastián le puso sal a las papas.",
        "La abuela tiene un abanico.",
        "La abuela busca la escoba.",
      ],
    },
    escritura: {
      trazos: ["B", "b"],
      palabraFinal: ["nube", "bien"],
    },
  },
  {
    // El cuadernillo enseña R en dos páginas separadas (sonido fuerte al inicio de
    // palabra, junto con "rr"; y sonido suave entre vocales o tras consonante, junto
    // con una página de combinaciones consonánticas que no agrega grafema nuevo) — acá
    // se combinan en una sola unidad para no repetir el botón "R" en Home.
    id: "r",
    order: 16,
    grafemas: ["R", "r"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "ra",
    fonemaRecordingKey: "r-R",
    lectura: {
      grid: [
        ["re", "ro", "ro", "ru", "ra", "ro"],
        ["ra", "ru", "ra", "ri", "ri", "re"],
        ["er", "ar", "or", "or", "ur", "ur"],
        ["er", "ir", "ur", "ar", "ir", "er"],
      ],
      palabras: [
        "ríe", "rey", "red", "real",
        "roca", "rica", "ropa", "ramo",
        "reina", "rana", "ratón", "radio",
        "rosas", "rápido", "respeto", "robot",
        "rodó", "rompió", "robó", "resbala",
        "rata", "rápida", "río", "rato",
        "rocas", "ronda", "rindió", "respondió",
        "marido", "Marte", "por", "barco",
        "pared", "era", "dura", "feria",
        "puerta", "duró", "arena", "eres",
        "fuerte", "tarta", "basura", "perdido",
        "cuadrado", "cubierto", "puerto", "fueron",
        "lámpara", "dormitorio", "corta", "para",
        "torta", "carne", "padre", "leer",
      ],
      oraciones: [
        "¡Un ratón se subió a la cama!",
        "Manuel lee rápido.",
        "La reina respondió con respeto.",
        "Papá le regaló un ramo de rosas a mamá.",
        "La moneda rodó por el suelo.",
        "Mi tía me llevó a la feria.",
        "Mi perro se sube lentamente al sillón para comer carne de la mesa.",
        "Pedro lee el diario todos los días.",
        "El perro duerme todo el día.",
        "Valeria come en un restaurante.",
        "El faro ilumina el camino de los barcos.",
        "Melina le lee el menú a Roberto.",
        "El amor nos une.",
      ],
    },
    escritura: {
      trazos: ["R", "r"],
      palabraFinal: ["rana", "rata", "tarta", "amor"],
    },
  },
  {
    id: "rr",
    order: 17,
    grafemas: ["rr"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "rra",
    fonemaRecordingKey: "rr-R",
    lectura: {
      grid: [
        ["orra", "arre", "orra", "arre", "orri", "orri"],
        ["arre", "orri", "orra", "orra", "orri", "arre"],
      ],
      palabras: [
        "perro", "torre", "corre", "carro",
        "tarro", "corro", "barro", "tierra",
        "correo", "carreta", "corrió", "marrón",
        "perros", "corremos", "derrite", "enterrado",
      ],
      oraciones: [
        "El perro corre rápido.",
        "El barro es marrón.",
        "La torre es rosa.",
        "El abuelo se fue al correo.",
        "Tenemos un tarro con limonada.",
      ],
    },
    escritura: {
      trazos: ["rr"],
      palabraFinal: ["perro", "torre"],
    },
  },
  {
    id: "f",
    order: 18,
    grafemas: ["F", "f"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "fa",
    lectura: {
      grid: [
        ["ef", "fi", "af", "fo", "fe", "uf"],
        ["ef", "fu", "if", "fe", "of", "fa"],
      ],
      palabras: ["fiesta", "café", "sofá", "futbolista", "fui", "fue", "falda", "elefante", "familia", "fines", "desafíos", "final"],
      oraciones: [
        "Mi familia come pescado en las fiestas",
        "Sofía tiene una falda linda.",
        "La fiesta fue buena.",
        "¡No me cuentes el final!",
      ],
    },
    escritura: {
      trazos: ["F", "f"],
      palabraFinal: ["foto", "final"],
    },
  },
  {
    id: "v",
    order: 19,
    grafemas: ["V", "v"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "va",
    fonemaRecordingKey: "v-b",
    lectura: {
      grid: [
        ["vu", "vo", "ev", "uv", "iv", "ov"],
        ["uv", "av", "ve", "vi", "va", "ev"],
      ],
      palabras: [
        "va", "vi", "vio", "ven",
        "voy", "voló", "lava", "vive",
        "vino", "novia", "vuela", "viene",
        "viven", "vamos", "selva", "vende",
        "nuevo", "viento", "vuelta", "viendo",
        "ventana", "olvides", "televisión", "remuevo",
        "vaca", "vestido", "vemos", "todavía",
      ],
      oraciones: [
        "Natalia se lava los dientes.",
        "El abuelo está viendo una película en la televisión.",
        "Viviana vende vestidos de novia.",
      ],
    },
    escritura: {
      trazos: ["V", "v"],
      palabraFinal: ["voy", "vaca"],
    },
  },
  {
    id: "ll",
    order: 20,
    grafemas: ["ll"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "lla",
    fonemaRecordingKey: "ll-L",
    lectura: {
      grid: [
        ["llu", "llo", "lli", "llo", "lle", "lla"],
        ["lle", "lle", "lla", "lla", "llu", "lli"],
      ],
      palabras: [
        "ella", "ellas", "ellos", "allí",
        "llama", "silla", "pollo", "llena",
        "lleno", "llamo", "sello", "tallo",
        "calle", "llave", "lleva", "toalla",
        "anillo", "llamó", "semilla", "lluvia",
        "llamado", "caballo", "llamaba", "apellidos",
        "ballena", "llenó", "relleno", "bellos",
      ],
      oraciones: [
        "Ella alimentó a la llama con semillas.",
        "El café está lleno de espuma.",
        "Me seco los pies con una toalla.",
      ],
    },
    escritura: {
      trazos: ["ll"],
      palabraFinal: ["calle", "silla"],
    },
  },
  {
    id: "g",
    order: 21,
    grafemas: ["G", "g"],
    fonemaEsPlaceholder: true,
    fonemaFallback: "ga",
    fonemaRecordingKey: "g-g",
    lectura: {
      grid: [
        ["glu", "ug", "gru", "go", "ig", "ga"],
        ["gó", "gla", "glo", "gri", "eg", "og"],
      ],
      palabras: [
        "algo", "lago", "agosto", "gato",
        "agua", "gusta", "largo", "amiga",
        "lugar", "amigo", "gusto", "salgo",
        "algún", "pagar", "colgar", "tengo",
        "goles", "luego", "gustó", "gallina",
        "seguro", "alguna", "llegada", "preguntar",
        "alguno", "apagar", "soga", "logró",
      ],
      oraciones: [
        "El dragón vuela sobre la torre.",
        "La gaviota nos robó las papas fritas.",
        "Los gatos pueden trepar alto.",
        "Antonio se olvidó de alimentar a la gallina.",
        "Camila le preguntó sobre la Luna al profesor.",
        "Mamá, gané un trofeo de tenis.",
        "Martín tiene buenos amigos.",
        "Victoria metió todos los goles.",
        "El elefante es un animal muy grande con trompa.",
        "Pepe ama la música. Un día, Pepe encontró un piano en su casa. Pensó en aprender a tocar el piano. Luego de un tiempo, Pepe tocaba todos los días. Luego, en solo dos meses, Pepe podía tocar el piano bien.",
      ],
    },
    escritura: {
      trazos: ["G", "g"],
      palabraFinal: ["gato", "tigre"],
    },
  },
];
